### PR TITLE
Remove verification and welcome messages

### PR DESCRIPTION
**Pull request by GRA0007**
Using Discord's built-in verification now

### CODE REVIEW

**Review by giraugh — APPROVED** [review]
Looks good to me. Just removes the verification functionality?

**Comment by GRA0007** [comment]
Yep pretty much

**Comment by giraugh** [comment]
RIP the bit server welcome messages though ;(

Did we discuss having the bot DM new members to provide info about the server or was that too distracting / too much for new discord users?

**Comment by GRA0007** [comment]
It was doing that, but I figure it was just overwhelming people, and I
think most of them were failing anyway because people had disabled DMs from
non-friend members

**Pull request merged**
